"""Abstract vector store interface (placeholder)."""
from __future__ import annotations
from typing import List, Tuple, Dict, Any, Protocol


class VectorStore(Protocol):
    def add(self, vectors: List[List[float]], payloads: List[Dict[str, Any]]) -> None: ...
    def search(self, vector: List[float], top_k: int = 5) -> List[Tuple[Dict[str, Any], float]]: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
